### ISSUE TITLE
Occasional "Unreachable Host" error

### ISSUE THREAD

**Issue by kylegibson** [algolia/algoliasearch-client-python#42] opened 2016-03-14 02:21 UTC
AlgoliaException: Unreachable hosts: {'****-1.algolianet.com': "SSLError: hostname '****-1.algolianet.com' doesn't match either of '*.algolia.io', '*.algolia.net'", '****-3.algolianet.com': "SSLError: hostname '****-3.algolianet.com' doesn't match either of '*.algolia.io', '*.algolia.net'", '****-2.algolianet.com': "SSLError: hostname '****-2.algolianet.com' doesn't match either of '*.algolia.io', '*.algolia.net'", '****.algolia.net': "ReadTimeout: HTTPSConnectionPool(host='****.algolia.net', port=443): Read timed out. (read timeout=1)"}

How can I prevent this error from happening?

Let me know if there's any more information I can provide.

**Comment by PLNech** [comment] 2016-03-14 11:12
Hi @kylegibson,
I indeed need more information to debug this, could you send an email with this error and your Application ID at support@algolia.com? I'll be on the other side to continue this conversation ;)

**Comment by kylegibson** [comment] 2016-03-14 15:54
Email sent. Thanks!

**Comment by PLNech** [comment] 2016-03-15 10:16
﻿The issue was caused by missing SNI support, which is [included in `python2.7.9` and higher](https://www.python.org/downloads/release/python-279/). 

Fixed by upgrading to python 2.7.9+.

**Closed by PLNech** 2016-03-15 10:16 UTC
